### ISSUE TITLE
Site font + broken link

### ISSUE THREAD

**Issue by sicin** [ytliu0/ChineseCalendar#12]
**Amazing resources, thank you!**

There is a visual bug that is happening all over the site with regard to pinyin:
![image](https://user-images.githubusercontent.com/60555965/104622528-ad240e00-5691-11eb-8ee7-6be2231d280e.png)
![image](https://user-images.githubusercontent.com/60555965/104622832-0724d380-5692-11eb-8310-73aa00149a59.png)
Looks like Verdana doesn't show the 3rd tone properly. Perhaps having Arial as the main font could solve the problem. (Or even adding Noto Sans and combining it then with Noto CJK for most optimal typography)

On another note, I'm surprised you are using `1 + mod(y+6, 10)` for stem and `1 + mod(y+8, 12)` for branch. Is there a particular reason for this? Why not use this method: https://zh.wikipedia.org/wiki/%E5%B9%B2%E6%94%AF#%E8%A5%BF%E6%9B%86%E2%86%92%E5%B9%B2%E6%94%AF%E7%B4%80%E5%B9%B4

Also, `<a href="Era_names.html">` should be changed to `<a href="era_names.html">` in others.html. Otherwise the link is dead.

**Comment by ytliu0** [comment]
Thanks for pointing out the display problem. I am primarily using Firefox and the display is fine. However, when I tested it with other browsers in 2018 the display was fine. So sometime later it failed to work with other browsers. It seems like using ariel as the primary font does fix the problem. Thanks for pointing out the Era_names mistake as well.

As for the calculation of the sexagenary year cycle. There are infinite numbers of formulae you can use. The general formulae for the stem and branch numbers are 1 + mod(y+6+10j, 10) and 1 + mod(y+8+12k, 12), where j and k are arbitrary integers. From the computational point of view, it's actually preferably to use j=72 and k=60, making stem = 1 + mod(y+726, 10) and branch = 1 + mod(y + 728, 12). The reason is that the modulo operation n % m in javascript (also in C++ and possibly in python) returns a negative number when n < 0 and m > 0, which messes up the counting. This is not a big deal. You just add 10 or 12 to the numbers when they are negative. Since years can range from -721 to 2200 here, adding 726 and 728 will make them all positive in the operation and I don't need to deal with negative numbers.

The method stated in your link works fine as well. However, the extra rules (餘0則視為第10個) and (餘0則視為第12個) mean that you'll have to deal with 0 in addition to negative numbers.

Edited to add:
Just verified that python's modulo operation works well for negative numbers. So the following python function works for any Western year y.
```
def sexagenary_year(y):
    s = ["jia", "yi", "bing", "ding", "wu", "ji", "geng", "xin", "ren", "gui"]
    b = ["zi", "chou", "yin", "mao", "chen", "si", "wu", "wei", "shen", "you", "xu", "hai"]
    return s[(y+6) % 10]+" "+b[(y + 8) % 12]
```
sexagenary_year(2021) returns 'xin chou'

sexagenary_year(-76) returns 'jia chen'

The function will be slightly more complicated if Wikipedia's formula is used instead.
